connection: &connection
  adapter: postgresql
  host: localhost
  username: postgres
  password: postgres
  encoding: utf8
  min_messages: warning #magic sauce

development:
  database: cable
  <<: *connection

test:
  database: cable_test
  <<: *connection

production:
  adapter: postgresql
  database: <%= ENV['PG_DB'] %>
  username: <%= ENV['PG_USER'] %>
  password: <%= ENV['PG_PASSWORD'] %>
  host: localhost
  pool: 5
  timeout: 5000

